language: python
python:
  - "2.6"
  - "3.6"
install:
  - pip install pytest-cov
  - pip install codecov
  - pip install jinja2
  - pip install basis_set_exchange
script:
  - PYTHONPATH="src/:$PYTHONPATH" pytest --cov-report=xml --cov=mqm
  - codecov
